In [2]:
import matplotlib.pyplot as plt
import torch
from torch.utils.data import Dataset
from torch.utils.data import DataLoader
torch.manual_seed(42)

# Creating a function f(X) with a slope of -5
X = torch.arange(-5, 5, 0.1).view(-1, 1)
func = -5 * X
# Adding Gaussian noise to the function f(X) and saving it in Y
Y = func + 0.4 * torch.randn(X.size())

w = torch.tensor(-10.0, requires_grad=True)
b = torch.tensor(-20.0, requires_grad=True)

# defining the function for forward pass for prediction
def forward(x):
    return w * x + b

# evaluating data points with Mean Square Error (MSE)
def criterion(y_pred, y):
    return torch.mean((y_pred - y) ** 2)

# Creating our dataset class
class Build_Data(Dataset):
    # Constructor
    def __init__(self):
        self.x = torch.arange(-5, 5, 0.1).view(-1, 1)
        self.y = -5 * X
        self.len = self.x.shape[0]
    # Getting the data
    def __getitem__(self, index):
        return self.x[index], self.y[index]
    # Getting length of the data
    def __len__(self):
        return self.len

# Creating DataLoader object
dataset = Build_Data()
train_loader_10 = DataLoader(dataset=dataset, batch_size=10)

step_size = 0.1
loss_MBGD_10 = []
n_iter = 20


In [3]:

for i in range(n_iter):
    # calculating loss as in the beginning of an epoch and storing it
    y_pred = forward(X)
    loss_MBGD_10.append(criterion(y_pred, Y).tolist())
    for x, y in train_loader_10:
        # making a prediction in forward pass
        y_hat = forward(x)
        # calculating the loss between original and predicted data points
        loss = criterion(y_hat, y)
        # backward pass for computing the gradients of the loss w.r.t to learnable parameters
        loss.backward()
        # updateing the parameters after each iteration
        w.data = w.data - step_size * w.grad.data
        b.data = b.data - step_size * b.grad.data
        # zeroing gradients after each iteration
        w.grad.data.zero_()
        b.grad.data.zero_()


In [ ]:

train_loader_20 = DataLoader(dataset=dataset, batch_size=20)

# Reset w and b
w = torch.tensor(-10.0, requires_grad=True)
b = torch.tensor(-20.0, requires_grad=True)

loss_MBGD_20 = []

for i in range(n_iter):
    # calculating loss as in the beginning of an epoch and storing it
    y_pred = forward(X)
    loss_MBGD_20.append(criterion(y_pred, Y).tolist())
    for x, y in train_loader_20:
        # making a prediction in forward pass
        y_hat = forward(x)
        # calculating the loss between original and predicted data points
        loss = criterion(y_hat, y)
        # backward pass for computing the gradients of the loss w.r.t to learnable parameters
        loss.backward()
        # updating the parameters after each iteration
        w.data = w.data - step_size * w.grad.data
        b.data = b.data - step_size * b.grad.data
        # zeroing gradients after each iteration
        w.grad.data.zero_()
        b.grad.data.zero_()

In [17]:
import torch
import torch.nn.functional as F

# Define a simple model
class SimpleModel(torch.nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc = torch.nn.Linear(10, 1)

    def forward(self, x):
        return torch.sigmoid(self.fc(x))

# Create an instance of the model
model = SimpleModel()

# Set up optimizer and loss function
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
criterion = torch.nn.BCELoss()

# Custom dataset (replace this with your own data loading mechanism)
# Assume X_train is a tensor of shape (num_samples, num_features)
# Assume y_train is a tensor of shape (num_samples, 1)
X_train = torch.rand((100, 10))
y_train = torch.randint(0, 2, (100, 1), dtype=torch.float)

# Training loop
batch_size = 32
num_epochs = 20

for epoch in range(num_epochs):
    for batch_start in range(0, len(X_train), batch_size):
        # Create a mini-batch
        batch_end = min(batch_start + batch_size, len(X_train))
        inputs = X_train[batch_start:batch_end]
        targets = y_train[batch_start:batch_end]

        # Zero gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(inputs)

        # Compute loss
        loss = criterion(outputs, targets)

        # Backward pass
        loss.backward()

        # Update weights
        optimizer.step()

    # Print the loss at the end of each epoch
    print(f'Epoch {epoch + 1}/{num_epochs}, Loss: {loss.item()}')


Epoch 1/20, Loss: 0.6633396744728088
Epoch 2/20, Loss: 0.6632982492446899
Epoch 3/20, Loss: 0.6632441878318787
Epoch 4/20, Loss: 0.6631776690483093
Epoch 5/20, Loss: 0.6630991101264954
Epoch 6/20, Loss: 0.6630086302757263
Epoch 7/20, Loss: 0.6629065275192261
Epoch 8/20, Loss: 0.6627931594848633
Epoch 9/20, Loss: 0.6626687049865723
Epoch 10/20, Loss: 0.6625335216522217
Epoch 11/20, Loss: 0.6623878479003906
Epoch 12/20, Loss: 0.662231981754303
Epoch 13/20, Loss: 0.6620661616325378
Epoch 14/20, Loss: 0.6618906259536743
Epoch 15/20, Loss: 0.6617057919502258
Epoch 16/20, Loss: 0.6615117788314819
Epoch 17/20, Loss: 0.661309003829956
Epoch 18/20, Loss: 0.6610974669456482
Epoch 19/20, Loss: 0.6608775854110718
Epoch 20/20, Loss: 0.6606496572494507


In [28]:
X_train = torch.tensor([1,2,3,4])

In [29]:
torch.stack([X_train,X_train])

tensor([[1, 2, 3, 4],
        [1, 2, 3, 4]])

In [30]:
inputs

tensor([[0.2361, 0.2371, 0.7419, 0.4869, 0.0195, 0.2144, 0.2686, 0.0361, 0.5640,
         0.6782],
        [0.4083, 0.3010, 0.4970, 0.1029, 0.1955, 0.4886, 0.9442, 0.3462, 0.7478,
         0.3032],
        [0.3669, 0.0240, 0.9142, 0.9869, 0.4895, 0.8177, 0.9090, 0.7484, 0.7575,
         0.0240],
        [0.0302, 0.1162, 0.6564, 0.0675, 0.1183, 0.2576, 0.0392, 0.5007, 0.5721,
         0.2074]])

In [31]:
X_train

tensor([1, 2, 3, 4])

In [ ]:

model=GNN_Classifier()
learning_rate=0.001
optimizer=torch.optim.Adam(model.parameters(),lr=learning_rate,weight_decay=5e-10)
criterion=torch.nn.BCELoss()
best_score=0

test_lost_list = []
train_lost_list = []
print_size=1
model.train() 
for epoch_num in range(10):
    epoch_accuracy = []
    epoch_pred_prob = []
    epoch_loss= 0
    
    for user_count,question_sequence in enumerate(users_question_sequence_train_lists):
        question_sequence_len=question_sequence.shape[1]
        optimizer.zero_grad()   

        out=model(data.x_dict, data.edge_index_dict,lookback,question_sequence) 
        target_answers=torch.tensor([question_sequence[2][lookback:]],dtype=torch.float).view(-1,1).float()
        loss=F.binary_cross_entropy(out,target_answers)
        loss.backward()
        optimizer.step()
        
        accuracy =(out.view(1,-1)[0].detach().round() ==  target_answers.view(1,-1)[0])*1
        
        train_loss = loss.item()
        epoch_loss =  epoch_loss + train_loss
        epoch_accuracy.extend(accuracy)
        epoch_pred_prob.extend(out.view(1,-1)[0].detach().tolist())
        
        test_loss,test_peformance=test(model)
        
        
        
    if (epoch_num+1)%print_size==0:
        epoch_loss =epoch_loss
        epoch_mean_acc = np.mean(epoch_accuracy)
        
        roc_auc=roc_auc_score(target_answer_list,epoch_pred_prob)
        
        print(f'Train epoch_num {epoch_num+1} | loss { epoch_loss/train_sequnce_len :.5f} | accuracy {epoch_mean_acc :.3f} | roc_auc {roc_auc :.3f} ')
        
        print(test_peformance)
        print('\n')
        
    test_lost_list.append(test_loss)
    train_lost_list.append(epoch_loss/train_sequnce_len)

    
            

In [ ]:
class GNN_Classifier(nn.Module):
    def __init__(self):
        super(GNN_Classifier, self).__init__()
        
        self.model_embedding=GNN()
        self.model_embedding = to_hetero(self.model_embedding, data.metadata(),aggr='max')
        self.classifer = Classifer()

    def forward(self, x,edges,lookback,question_sequence):
        question_sequence_len=question_sequence.shape[1]
        node_embeddings = self.model_embedding(x,edges)
        
        stacked_sample_features=[]
        
        for question_num in range(lookback,question_sequence_len):
            features_concat_list=[]
            
            for i in range(lookback+1):

                lo=question_sequence[0][question_num-i]
                atom=question_sequence[1][question_num-i]
                prev_answer=torch.tensor([question_sequence[2][question_num-1-i]]).float()
                
                features_concat_list.extend([node_embeddings['atom'][atom]])
                features_concat_list.extend([node_embeddings['lo'][lo]])
                features_concat_list.extend([prev_answer])
                   
            user_embeddings=torch.cat(features_concat_list)
            
            stacked_sample_features.append(user_embeddings)
            
        stacked_sample_features= torch.stack( stacked_sample_features  )  
        
        
        rnn_outputs = self.classifer(stacked_sample_features)
    
        return rnn_outputs